<div style="display:block;width:100%;margin:auto;" direction=rtl align=center><br><br>
    <div  style="width:100%;margin:100;display:block;background-color:#fff0;"  display=block align=center>
        <table style="border-style:hidden;border-collapse:collapse;">
            <tr>
                <td  style="border: none!important;">
                    <img width=130 align=right src="https://i.ibb.co/yXKQmtZ/logo1.png" style="margin:0;" />
                </td>
                <td style="text-align:center;border: none!important;">
                    <h1 align=center><font size=5 color="skyblue">University of Tehran</i></font></h1>
                </td>
                <td style="border: none!important;">
                    <img width=170 align=left  src="https://i.ibb.co/wLjqFkw/logo2.png" style="margin:0;" />
                </td>
            </tr>
        </table>
    </div>
</div>

<h1 style = "color:orange;" dir = "ltr"> <b>
    Summer Class
</b> </h1>

<h1 style = "color:orange;" dir = "ltr"> <b>
    Python Tutorial
</b> </h1>

<h1 style = "color:orange;" dir = "ltr"> <b>
    Written by Babak Hosseini Mohtasham
</b> </h1>


<h1 style = "color:red;text-align: center;font-size:50px"> <b>
    Table of Contents
</b> </h1>

- [Numpy](#mt1)  

    - [What is numpy?](#st1)

    - [Installing Numpy](#st2)

    - [Make a Numpy array](#st3)

    - [Basics properties of a Numpy array](#st4)

    - [Basic functions of a Numpy array](#st5)

    - [Mathematical functions of Numpy](#st6)

    - [Random from Numpy](#st7)

<a id='mt1'></a>

<h1 style = "color:red;text-align: center;font-size:50px"> <b>
    Numpy
</b> </h1>

<a id='st1'></a>

<h1 style = "color:green;font-size:30px" dir = "ltr"> <b>
    What is numpy?:
</b> </h1>

**NumPy**, which stands for Numerical Python, is an open source library for Python. Numpy is one of the most popular Python packages among scientists and engineers. Numpy is consisted of a data structure called **array**. Numpy arrays are commonly used in data science and machine learning projects. Arrays are very similar to the list data structure built in Python, so why should we choose arrays over lists?
* Arrays use the priniciple of locality to store data at one continuous place in memory unlike lists, and that makes arrays way more efficient and faster than Python lists.
* Numpy's main functions are written in C/C++ programming languages and that makes it very fast.
* Arrays support many different mathematical operations such as the operations performed on matrices in linear algebra, also support of multi dimensions operations is critical for data analysis.
* Numpy has provided a very intuitive and simple api to use arrays and therefore many other famous packages such as Pandas and SKLearn are built on top of Numpy.

So now let's see how we can use Numpy in our own projects.

<a id='st2'></a>

<h1 style = "color:green;font-size:30px" dir = "ltr"> <b>
    Installing Numpy:
</b> </h1>

There are a few different ways to install Numpy the simplest one is to run the following command in a terminal:
```python
pip install numpy
```
Then you can import it in your Python project. Numpy is usually imported as np.

In [73]:
import numpy as np

<a id='st3'></a>

<h1 style = "color:green;font-size:30px" dir = "ltr"> <b>
    Make a Numpy array:
</b> </h1>

There are several different ways to make a numpy array:

1. Convert an existing data structure to a Numpy array. We can simply convert a list, tuple, set or almost any other data structure to an array simply by writing (don't put *): 
```python
np.array(*Our data structure*)
```

In [74]:
my_list = [1, 2, 3, 4, 5]
my_array_1 = np.array(my_list)

now let's print the array to see its elements. To print the elements of an array we can simply use the `print` function of Python

In [75]:
print(my_array_1)

[1 2 3 4 5]


2. Make an array of some **shape** filled with a specific value. The shape of an array is a tuple showing the number of elements in each dimension. We can make an array in this way by writing:
```python
np.full(*Shape*,*Value to fill*)
```

In [76]:
my_array_2_1 = np.full((2,3),5)
print(my_array_2_1)

[[5 5 5]
 [5 5 5]]


There are also `np.ones` and `np.zeros` functions which make an array filled with value 1 or 0.

In [77]:
my_array_2_2 = np.ones((3,2))
print(my_array_2_2)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [78]:
my_array_2_2 = np.zeros((2))
print(my_array_2_2)

[0. 0.]


3. Make an array filled with a specific value that has a shape like the shape of another array. This is like the previous function but here we give another array as input so the new array will have the same shape as the other array.
```python
np.full_like(*The array we want its shape*,*Value to fill*)
```

In [79]:
np.full_like(my_array_1, 5)

array([5, 5, 5, 5, 5])

Same as before there are also functions for filling arrays with 1 or 0 called `np.ones_like` and `np.zeros_like`.

In [80]:
np.ones_like(my_array_2_2)

array([1., 1.])

In [81]:
np.zeros_like(my_array_2_1)

array([[0, 0, 0],
       [0, 0, 0]])

4. Make a copy of another array. Like lists, if you write list_2=list_1 Python makes a shallow copy of list_1 so making any changes to one list causes the same changes to the other list. To make a deep copy of an array we can use the `copy` function.

In [82]:
print(my_array_1)
my_array_3_1 = my_array_1
my_array_3_2 = my_array_1.copy()
my_array_1[0]=100
print(my_array_3_1)
print(my_array_3_2)

[1 2 3 4 5]
[100   2   3   4   5]
[1 2 3 4 5]


Here we can see that changing the first element of my_array_1 to 100 also changed the first element of my_array_3_1 to 100 but it didn't affect my_array_3_2.

5. Make an identity matrix of shape N x N.
```python
np.identity(*N*)
```

In [83]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

It's also possible to make the identity array using `np.eye`. This function gets number of rows and columns(optional) as input.
```python
np.eye(*row*,*col*)
```

In [84]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

6. Make a list of elements from ranging from start(inclusive) to end(exclusive) incrementing by step.
```python
np.arange(*Start*,*End*,*Step*)
```

In [85]:
np.arange(0, 12,2)

array([ 0,  2,  4,  6,  8, 10])

The default values of Start and End are: 0 and 1.

In [86]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

7. Make an array of evenly spaced numbers over a specified interval(inclusive on both ends).
```python
np.linspace(*Start*,*End*,*Num*)
```

In [87]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

8. There are many other ways to create a Numpy arrays but, they are rarely used. Here are some of the other functions that can be used to create arrays: `np.asanyarray,np.asarray,np.asarray_chkfinite,np.ascontiguousarray,np.asfortranarray,np.asfarray,...`

<a id='st4'></a>

<h1 style = "color:green;font-size:30px" dir = "ltr"> <b>
    Basics properties of a Numpy array:
</b> </h1>

If we use the type() function of python on arrays it returns `numpy.ndarray` which means this is an n dimensional Numpy array.

In [88]:
type(my_array_1)

numpy.ndarray

Each array has a specific shape which can be seen using `np.shape`. The shape of an array is a tuple that each element of it is equal to the number of elements the array has in that dimension. For example if the shape of an array is (4,2,3) it means it has 4 elements in its first dimension, 2 elements in its second dimension and 3 elements in its last dimension.

In [89]:
my_list = [[1,2],[3,4],[5,6]]
my_array = np.array(my_list)
print(my_array.shape)

(3, 2)


We can index an array similar to lists. For accessing the ith element of a 1d array simply write `my_array[i]`.

In [90]:
my_list = [1,2,3]
my_array = np.array(my_list)
print(my_array[0])

1


If the array has more than one dimension we can access a specific element by having the indices in each dimension. If an element has indices i1,i2,...,in in each dimension we can access it by writing `my_array[i1,i2,...,in]`.

In [91]:
my_list = [[1, 2], [3, 4], [5, 6]]
my_array = np.array(my_list)
print(my_array[0, 1])

2


Same as lists it is also possible to access elements of an array using negative indices. The -ith element of an array is same as (number of elements in that dimension - i)th element of the array, equivalently we can say by using negative indexing we can count the elements of an array from the end.

In [92]:
my_list = [1, 2, 3]
my_array = np.array(my_list)
print(my_array[-1])

3


We can also use negative indices in a multi-dimensional array.

In [93]:
my_list = [[1, 2], [3, 4], [5, 6]]
my_array = np.array(my_list)
print(my_array[-2,-1])

4


Same as lists, arrays support slicing. We can access elements from a start index(inclusive) to an end index(exclusive) of an array placed by a specific number of steps apart, the following way: 
```python
array[*Start*:*End*:*Step*]
```
The default values of Start, Stop and End are: 0, length of array in that dimension and 1.

In [94]:
my_list = np.arange(10)
my_array = np.array(my_list)
print(my_array)
print(my_array[3:7])

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]


Numpy arrays can store different types of data. To see what the type of an array is we can write my_array.dtype.

In [95]:
np.dtype(my_array.dtype)

dtype('int32')

Below is a list of all data types in NumPy and the characters used to represent them.

* i - integer
* b - boolean
* u - unsigned integer
* f - float
* c - complex float
* m - timedelta
* M - datetime
* O - object
* S - string
* U - unicode string
* V - fixed chunk of memory for other type ( void )

When creating an array we can specify its data type.

In [96]:
my_array=np.arange(0,5,0.5,dtype='f')
my_array

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5], dtype=float32)

We can also convert from one dtype to another.

In [97]:
my_array.astype('i')

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4], dtype=int32)

<a id='st5'></a>

<h1 style = "color:green;font-size:30px" dir = "ltr"> <b>
    Basics functions of a Numpy array:
</b> </h1>

We can get the shape of an array by using the `np.shape` function.

In [98]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array.shape)

(2, 3)


We can also get the number of elements in an array using the `size` function of arrays. Note that the number of elements is equal to product of elements of the shape of array.

In [99]:
print(my_array.size)
print(np.prod(my_array.shape))

6
6


We can get the number of dimensions of an array by either using the `len` function of Python or using the `ndim` function of arrays. Note that the number of dimensions of an array is equal to the number of elements in its shape.

In [100]:
print(my_array.ndim)
print(len(my_array))
print(len(my_array.shape))

2
2
2


Numpy arrays can also be reshaped as long as the product of elements of shape before and after reshaping stays the same equivalently we can say as long as the number of elements stays the same.

In [101]:
my_array=my_array.reshape(3, 2)
print(my_array)

[[1 2]
 [3 4]
 [5 6]]


We can also change the number of dimensions by reshaping an array.

In [102]:
my_array = my_array.reshape((6))
print(my_array)

[1 2 3 4 5 6]


We can also put -1 for a specific dimension in that way the array will be reshaped such that the number of elements stays the same.

In [103]:
my_array = my_array.reshape((-1,2))
print(my_array)

[[1 2]
 [3 4]
 [5 6]]


Like lists, arrays also have append and insert functions but unlike lists, these operations are not done inplace for arrays.

np.append appends values to the end of an array.
```python
np.append(*my_array*,*Vlaues*)
```

In [104]:
my_array = np.arange(0, 5)
print(my_array)
my_array=np.append(my_array, 5)
print(my_array)

[0 1 2 3 4]
[0 1 2 3 4 5]


When working with multi-dimensional arrays we need to specify the dimension which we want the values to be appended in. We do this by giving a value to the axis argument of np.append and many other numpy functions. In a NumPy array, axis 0 is the first axis. Assuming that we’re talking about multi-dimensional arrays, axis 0 is the axis that runs downward down the rows. When we’re talking about 2-d and multi-dimensional arrays, axis 1 is the axis that runs horizontally across the columns and so on....

In [105]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array)
print('\n')
my_array = np.append(my_array, [[7, 8, 9]], axis=0)
print(my_array)

[[1 2 3]
 [4 5 6]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


If we'd written axis=1, we would have seen the following error:

`all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 1`

which is self-explanatory. To understand the difference between axis we can create a n*n array.

In [106]:
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(my_array)
print('\n')
print(np.append(my_array, [[-1, -2, -3]], axis=0))
print('\n')
print(np.append(my_array, [[-1], [-2], [-3]], axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [-1 -2 -3]]


[[ 1  2  3 -1]
 [ 4  5  6 -2]
 [ 7  8  9 -3]]


np.insert insert values along the given axis before the given indices.

In [107]:
my_array = np.arange(0, 5)
print(my_array)
my_array=np.insert(my_array, 1, 10)
print(my_array)

[0 1 2 3 4]
[ 0 10  1  2  3  4]


We can specify the axis same as before.

In [108]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array)
print('\n')
my_array = np.insert(my_array,1, [[7, 8, 9]], axis=0)
print(my_array)

[[1 2 3]
 [4 5 6]]


[[1 2 3]
 [7 8 9]
 [4 5 6]]


There are two main ways to join several Numpy arrays.

We can use the `np.concatenate` function.
```python
np.concatenate((*array_1*,*array_2*,...,*array_n),axis)
```

In [109]:
my_array_1 = np.array([1, 2, 3])
my_array_2 = np.array([4, 5, 6])
my_array_3 = np.concatenate((my_array_1, my_array_2), axis=0)
print(my_array_3)

[1 2 3 4 5 6]


Working with axes is same as before.

In [110]:
my_array_1 = np.array([[1, 2], [3, 4]])
my_array_2 = np.array([[5, 6], [7, 8]])
my_array_3 = np.concatenate((my_array_1, my_array_2),axis=0)
print(my_array_3)
print('\n')
my_array_3 = np.concatenate((my_array_1, my_array_2), axis=1)
print(my_array_3)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


[[1 2 5 6]
 [3 4 7 8]]


Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
```python
np.stack((*array_1*,*array_2*,...,*array_n),axis)
```

In [111]:
my_array_1 = np.array([1, 2, 3])
my_array_2 = np.array([4, 5, 6])
my_array_3 = np.stack((my_array_1, my_array_2), axis=0)
print(my_array_3)

[[1 2 3]
 [4 5 6]]


Split is the reverse operation of joining. By using the `np.split` function we can break an array into smaller arrays.
```python
np.split(*array*,*number of arrays after split*)
```

In [112]:
my_array = np.arange(6)
print(my_array)
print('\n')
print(np.split(my_array, 3,axis=0))

[0 1 2 3 4 5]


[array([0, 1]), array([2, 3]), array([4, 5])]


We can turn any n-dimensional array to a 1d array using the `flatten` function of arrays.

In [113]:
my_array = np.array([[1, 2], [3, 4]])
print(my_array)
print('\n')
print(my_array.flatten())

[[1 2]
 [3 4]]


[1 2 3 4]


We can sort arrays using `np.sort`(not inplace) or `sort` function of arrays(inplace).

In [114]:
my_array = np.array([4,3,2,1])
print(my_array)
print(np.sort(my_array))
print(my_array)

[4 3 2 1]
[1 2 3 4]
[4 3 2 1]


In [115]:
my_array.sort()
print(my_array)

[1 2 3 4]


We can also filter Numpy arrays by a condition and only get elements that satisfy the condition. Putting a condition on arrays in this way returns another array of same shape but each element is either True or False based on the condition.

In [116]:
print(my_array)
print(my_array % 2 == 0)
print(my_array < 3)

[1 2 3 4]
[False  True False  True]
[ True  True False False]


So by giving these boolean values as indices we can get the elements that satisfy the condition.

In [117]:
print(my_array[my_array % 2 == 0])
print(my_array[my_array < 3])

[2 4]
[1 2]


You can also use `np.where` to filter an array. This function returns the indices whoses elements satisfy the condition.

In [118]:
print(my_array)
print(np.where(my_array % 2 == 0))
print(np.where(my_array < 3))

[1 2 3 4]
(array([1, 3], dtype=int64),)
(array([0, 1], dtype=int64),)


As before we can get the elements themselves by giving these indices to the array.

In [119]:
print(my_array)
print(my_array[np.where(my_array % 2 == 0)])
print(my_array[np.where(my_array < 3)])

[1 2 3 4]
[2 4]
[1 2]


<a id='st6'></a>

<h1 style = "color:green;font-size:30px" dir = "ltr"> <b>
    Mathematical functions of Numpy:
</b> </h1>

In [120]:
my_array_1 = np.arange(5)
print(my_array_1)
my_array_2 = np.arange(5,10)
print(my_array_2)

[0 1 2 3 4]
[5 6 7 8 9]


We can add, subtract, divide or multiply two arrays element by element using the +, -, / or * operator. Note that if we used + between lists it would have joined them.

In [121]:
print(my_array_1 + my_array_2)
print(my_array_1 - my_array_2)
print(my_array_1 / my_array_2)
print(my_array_1 * my_array_2)

[ 5  7  9 11 13]
[-5 -5 -5 -5 -5]
[0.         0.16666667 0.28571429 0.375      0.44444444]
[ 0  6 14 24 36]


It's also possible to use the np functions for these operators.

In [122]:
print(np.add(my_array_1, my_array_2))
print(np.subtract(my_array_1, my_array_2))
print(np.divide(my_array_1, my_array_2))
print(np.multiply(my_array_1, my_array_2))

[ 5  7  9 11 13]
[-5 -5 -5 -5 -5]
[0.         0.16666667 0.28571429 0.375      0.44444444]
[ 0  6 14 24 36]


We can take the dot product by using the @ operator or by using the `np.dot` function.

In [125]:
print(my_array_1 @ my_array_2.reshape(5,1))
print(np.dot(my_array_1, my_array_2.reshape(5,1)))

[80]
[80]


We can take cross product by using `np.cross` function.

In [131]:
x = [1, 2, 3]
y = [4, 5, 6]
np.cross(x, y)

array([-3,  6, -3])

We can take absolute value of each element using `np.abs`.

In [132]:
np.abs([-1, -2, 3])

array([1, 2, 3])

We can find `min`, `max`, `mean`, `std`, `var` of an array.

In [134]:
my_array=np.arange(5)
print(my_array)
print(my_array.mean())
print(np.mean(my_array))
print(my_array.min())
print(my_array.max())
print(my_array.std())
print(my_array.var())

[0 1 2 3 4]
2.0
2.0
0
4
1.4142135623730951
2.0


We can get the sum of elements or product of elements of an array using `sum` or `prod` functions.

In [135]:
print(my_array.sum())
print(my_array.prod())

10
0


We can get the transpose of an array by using `T` or using `np.transpose`.

In [140]:
my_array=np.array([[1, 2], [3, 4]])
print(my_array)
print('\n')
print(my_array.T)
print('\n')
print(np.transpose(my_array))

[[1 2]
 [3 4]]


[[1 3]
 [2 4]]


[[1 3]
 [2 4]]


We can get cumulative sum or product by using `cumsum` or `cumprod`.

In [141]:
print(my_array.cumsum())
print(my_array.cumprod())

[ 1  3  6 10]
[ 1  2  6 24]


We can get `log` or `exp` of elements of an array.

In [147]:
print(np.log(my_array))
print('\n')
print(np.exp(my_array))

[[0.         0.69314718]
 [1.09861229 1.38629436]]


[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


We can convolve on array to another using `np.convolve`.

In [173]:
my_array_1 = np.arange(10)
my_array_2 = np.arange(3)
np.convolve(my_array_1,my_array_2)

array([ 0,  0,  1,  4,  7, 10, 13, 16, 19, 22, 25, 18])

There are many other mathematical functions that numpy sopprts and you can easily find them and use them in your projects. There also many functions related to linear algebra in `np.linalg` class.

<a id='st7'></a>

<h1 style = "color:green;font-size:30px" dir = "ltr"> <b>
    Random from Numpy:
</b> </h1>

Numpy also has many functions related to probability and randomness. In np.random functions usually get the size parameter which is the shape of the array.

In [149]:
from numpy import random

We can set the random seed in the beginning so that our result would be reproducible.

In [167]:
random.seed(0)

We can create an array of some shape filled with random numbers sampled from a famous distribution.

`rand(*Shape*)` samples from uniform distribution over [0,1).

In [154]:
random.rand(2, 3)

array([[0.39601663, 0.04148433, 0.00253125],
       [0.2411368 , 0.29498103, 0.66959385]])

`randint(*Low*,*High*,*Shape*)` samples from discrete uniform distribution over [low,high)

In [155]:
random.randint(0, 10, (2, 3))

array([[0, 6, 3],
       [8, 0, 1]])

`randn(*Shape*)` samples from standard normal distribution.

In [157]:
random.randn(2, 3)

array([[ 0.11266913,  0.72338762, -1.75682342],
       [-1.38526859,  0.46725728, -0.00865833]])

We can also sample from many other famous distributions by giving their parameters and shape.

In [161]:
print(random.binomial(10, 0.5, (2, 3)))
print(random.normal(2, 0.5, (2, 3)))
print(random.poisson(2, (2, 3)))
print(random.uniform(2,3, (2, 3)))

[[4 7 7]
 [4 4 4]]
[[1.55430343 2.3984856  2.28495172]
 [2.90915565 1.24648389 2.49826987]]
[[2 3 3]
 [4 3 3]]
[[2.10634929 2.88268869 2.24024582]
 [2.88695041 2.20108213 2.82711473]]


We can sample from an array by giving the probabilities of choosing each element using the `choice` function.

In [164]:
random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(10))

array([3, 5, 7, 7, 7, 7, 3, 5, 7, 7])

We can shuffle an array using `shuffle`. Note that this function shuffles inplace but we can use `permutation` that gives a random permutation and is not inplace.

In [172]:
my_array=np.arange(5)
print(random.permutation(my_array))
print(my_array)
random.shuffle(my_array)
print(my_array)

[4 2 3 1 0]
[0 1 2 3 4]
[2 3 4 1 0]
